language: node_js
node_js:
  "node"
script:
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist
  github_token: $GH_TOKEN # Set in travis-ci.org dashboard
  fqdn: apps.vechain.org
  on:
    branch: master